# Generated by Django 4.0.5 on 2023-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=150)),
                ('hostel', models.CharField(max_length=250)),
            ],
        ),
    ]
