# Generated by Django 4.0.5 on 2023-08-16 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlcf_online', '0003_info_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='location',
            field=models.CharField(choices=[('Location1', 'L1'), ('Location2', 'L2')], default='null', max_length=9),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_no',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits without spaces or dashes and must be exactly 11 digits', regex='^\\d{11}$')]),
        ),
    ]
