# Generated by Django 4.0.5 on 2023-08-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlcf_online', '0005_alter_info_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='location',
            field=models.CharField(choices=[('Location1', 'L1'), ('Location2', 'L2')], default=None, max_length=9, null=True),
        ),
    ]
